--- # webserver
server:
  port: 8080
  context-path: /

--- # logging
logging:
  level:
    org.springframework.web.servlet.mvc: debug
    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://221.178.232.93:3307/mscx_ordermgr?useSSL=false
    username: order_root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持

--- # eureka
spring:
    application:
      name: mscx-order-api
      groupName: mscx_center


eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      registry-fetch-interval-seconds: 10   #生产环境上，这个值得设为30
      initial-instance-info-replication-interval-seconds: 5  #生产环境上，这个值得设为10
      serviceUrl:
        defaultZone: http://mscx-eureka-server-mgr.eastdc.cn:82/eureka/,http://mscx-eureka-server-mgr-2.eastdc.cn:82/eureka/
      healthcheck:
        enabled: true
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
      lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
    server:
      waitTimeInMsWhenSyncEmpty: 0
      registrySyncRetries: 0

mscx-order-mgr:
    ribbon:
      serverListRefreshInterval: 5000   #生产环境上，这个值得设为30000

--- # platform
platform:
  invokeTrace:
    enabled: true
    url: http://invoke-trace2.eastdc.cn:82/invoke.do

--- # swagger2
swagger:
  show: true